"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v_!5^&3h-^omylm4^d3o$_ns=d+s-fjy6k#qtg!k8uwmbl!ug$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # 允许任何主机访问（方便局域网内联调前端）


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'sslserver',     # HTTPS 自签证书，手机 PWA 安装需要
    'charging_system',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # 🌟 3. 跨域处理中间件（必须放在 CommonMiddleware 之前）
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 🌟 4. 跨域白名单：允许所有前端网页来源直接异步请求你们的后端接口
CORS_ALLOW_ALL_ORIGINS = True 

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# 系统采用默认的高效轻量物理数据库 SQLite (项目根目录下的 db.sqlite3)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'zh-hans'  # 🌟 切换为中文语言环境（这样 Django 后台会变成中文，方便验收）

TIME_ZONE = 'Asia/Shanghai' # 🌟 切换为中国标准时间（分时计费算法的时钟对齐极重要）

USE_I18N = True

USE_TZ = False # 🌟 关闭时区硬转换，使本地写入数据库的时间就是本地时间，防止算账时差错乱


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'