# Generated by Django 6.0.6 on 2026-06-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillRecord',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_id', models.CharField(max_length=20, verbose_name='车辆ID')),
                ('pile_id', models.CharField(max_length=20, verbose_name='充电桩ID')),
                ('charge_amount', models.FloatField(verbose_name='充电量(度)')),
                ('start_time', models.DateTimeField(verbose_name='充电开始时间')),
                ('end_time', models.DateTimeField(verbose_name='充电结束时间')),
                ('charge_duration_minutes', models.FloatField(verbose_name='充电持续时间(分钟)')),
                ('charge_fee', models.FloatField(verbose_name='分时充电费(元)')),
                ('service_fee', models.FloatField(verbose_name='固定服务费(元)')),
                ('total_fee', models.FloatField(verbose_name='总费用(元)')),
            ],
        ),
        migrations.CreateModel(
            name='ChargePile',
            fields=[
                ('pile_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='充电桩ID')),
                ('mode', models.CharField(choices=[('F', '快充'), ('T', '慢充')], max_length=2, verbose_name='充电桩类型(F/T)')),
                ('status', models.CharField(choices=[('IDLE', '空闲'), ('CHARGING', '充电中'), ('FAULT', '故障')], default='IDLE', max_length=20, verbose_name='运行状态')),
                ('current_car_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='当前正在充电的车辆ID')),
                ('total_charge_amount', models.FloatField(default=0.0, verbose_name='累计充电量(度)')),
                ('total_charge_times', models.IntegerField(default=0, verbose_name='累计充电次数')),
                ('total_charge_duration_minutes', models.FloatField(default=0.0, verbose_name='累计充电时长(分钟)')),
            ],
        ),
        migrations.CreateModel(
            name='CarState',
            fields=[
                ('car_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='车辆ID')),
                ('mode', models.CharField(choices=[('F', '快充'), ('T', '慢充')], default='T', max_length=2, verbose_name='充电模式')),
                ('request_amount', models.FloatField(default=0.0, verbose_name='请求充电量(度)')),
                ('charged_amount', models.FloatField(default=0.0, verbose_name='已充电量(度)')),
                ('status', models.CharField(choices=[('WAITING', '等候区排队中'), ('QUEUEING', '充电区专属队列排队中'), ('CHARGING', '正在充电'), ('FINISHED', '充电完成'), ('FAULT_WAITING', '故障再调度等待中')], default='WAITING', max_length=20, verbose_name='车辆状态')),
                ('queue_index', models.IntegerField(default=0, verbose_name='在专属队列中的排队顺位(1-4)')),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='发起充电请求时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始充电时间')),
                ('last_update_time', models.DateTimeField(blank=True, null=True, verbose_name='上一次计算电量的结算点')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束充电/移出系统时间')),
                ('total_fee', models.FloatField(default=0.0, verbose_name='当前已产生的累计总费用')),
                ('pile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_in_queue', to='charging_system.chargepile', verbose_name='所属充电桩')),
            ],
        ),
    ]
